Neovim fixes and finalized waybar-preview script.

diff --git a/scripts/colorsnap/colorsnap b/scripts/colorsnap/colorsnap
--- a/scripts/colorsnap/colorsnap
+++ b/scripts/colorsnap/colorsnap
@@ -1,88 +1,63 @@
 #!/usr/bin/env sh
 #
-# Simple color picker that will copy the color to clipboard (and show it in a
-# notification, if such a daemon is installed). By default it copies the color
-# in hex format, but flags can be used to specify another format.
+# Simple color picker using slurp. Copies the color to clipboard and shows a notification if a
+# daemon is found. Hex format unless using the --rgb (-r) flag.
 #
 
-set -eu
-
-errors=false
-option_hex=true
-option_rgb=false
-option_help=false
-has_notify=false
-has_convert=false
-has_copy=false
 usage="USAGE:
     $(basename "$0") [options]
 
 DESCRIPTION:
-    Click anywhere on the screen to get the color copied to clipboard (and a notificaion shown on screen if mako or similar is installed). You may specify which color format to receive using the flags (hex is default).
+    Click a color to copy it to clipboard. A notificaion is displayed if a notification daemon is installed. Hex format is used unless the --rgb (-r) flag is used.
 
 OPTIONS:
-    --help, -h    Show this help text
-    --hex, -x     Get color in hex format (default)
-    --rgb, r      Get color in RGB format"
+    --rgb, -r     Use RGB format
+    --help, -h    Show this help text"
 
-# Check dependencies
-! [ -x "$(command -v notify-send)" ] || has_notify=true
-! [ -x "$(command -v convert)" ] || has_convert=true
-! [ -x "$(command -v wl-copy)" ] || has_copy=true
-
-if [ "$has_convert" = false ]; then
-  echo "Cannot find convert command. Please make sure ImageMagick is installed."
-  exit 1
-fi
-
-for arg in "$@"
-do
+for arg in "$@"; do
   case $arg in
-    -h|--help)
-    option_help=true
+  -h | --help)
+    printf "%s" "$usage"
+    exit 0
     shift
     ;;
-    -x|--hex)
-    option_hex=true
+  -r | --rgb)
+    format="rgb"
     shift
     ;;
-    -r|--rgb)
-    option_rgb=true
-    shift
-    ;;
-    *)
-    TARGET+=("$1")
+  *)
     shift
     ;;
   esac
 done
 
-# Show help if the --help (or -h) flag is used
-if [ "$option_help" = true ]; then
-  echo "$usage"
-  exit 0
+# Make sure ImageMagick dependency is available
+if ! [ -x "$(command -v convert)" ]; then
+  printf "%s" "Cannot find convert command. Please make sure ImageMagick is installed."
+  exit 1
 fi
 
+# Use slurp to pick position, grim to get pixel image, and convert to get color
 color=$(grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | tail -n 1) 2>/dev/null
 
-if [ "$option_rgb" = true ]; then
-  # RGB value
-  output="rgb$(echo $color | cut -d' ' -f2)"
+# Fetch color as hex and RGB
+rgb="$(printf "%s" "$color" | sed 's,^.*\([0-9]\+\)\,\([0-9]\+\)\,\([0-9]\+\).*$,rgb(\1\, \2\, \3),g')"
+hex="$(printf "%s" "$color" | sed 's,^.*\(#\w\{6\}\).*$,\1,g')"
+
+if [ "$format" = "rgb" ]; then
+  primary="$rgb"
+  secondary="$hex"
 else
-  # Hex value
-  output="$(echo $color | cut -d' ' -f3)"
+  primary="$hex"
+  secondary="$rgb"
 fi
 
-if [ "$has_notify" = true ]; then
-  notify-send -a "Color Snap" -t 2000 --urgency=low --icon=gtk-dialog-info "$output"
-fi
+# Copy to clipboard
+[ -x "$(command -v wl-copy)" ] && \
+  wl-copy "$primary"
 
-if [ "$has_copy" = true ]; then
-  wl-copy "$output"
-fi
-
-if $errors; then
-	exit 1
-fi
+# Show notification
+[ -x "$(command -v notify-send)" ] && \
+  notify-send --urgency low --icon deepin-picker "$primary" "$secondary"
 
 exit 0
