Adding foot terminal emulator with Catppuccin colors, for trying it out.

diff --git a/scripts/nix-preview/nix-preview b/scripts/nix-preview/nix-preview
--- a/scripts/nix-preview/nix-preview
+++ b/scripts/nix-preview/nix-preview
@@ -11,9 +11,17 @@ set -eu
 trap 'printf "\n\n%s\n\n" "Error: Preview mode not enabled."; exit 1;' ERR
 trap 'printf "\n\n%s\n\n" "Cancelled: Preview mode not enabled."; exit 1;' SIGINT
 
-notestart=$(tput bold; tput setaf 0; tput setab 3)
+notestart=$(
+  tput bold
+  tput setaf 0
+  tput setab 3
+)
 noteend=$(tput sgr0)
-titlestart=$(tput bold; tput setaf 0; tput setab 6)
+titlestart=$(
+  tput bold
+  tput setaf 0
+  tput setab 6
+)
 titleend=$(tput sgr0)
 cleanupfile="$HOME/.nix-preview-cleanup"
 cleanupbang="#!/usr/bin/env sh"
@@ -29,15 +37,14 @@ OPTIONS:
     --cleanup-file, -c  Path to generate cleanup script at (default: ~/.nix-preview-cleanup)
 "
 
-for arg in "$@"
-do
+for arg in "$@"; do
   case $arg in
-    # Cleanup script path
-    -c|--cleanup-file)
+  # Cleanup script path
+  -c | --cleanup-file)
     shift
     cleanup="$1"
     ;;
-    -h|--help)
+  -h | --help)
     printf "\n%s\n" "$usage"
     exit 0
     ;;
@@ -48,7 +55,7 @@ done
 printf "\n%s\n" "$titlestart Configuration preview mode ""$titleend"
 
 # Get full cleanup file path and make sure it's valid
-if ! realpath "$cleanupfile" > /dev/null 2>&1; then
+if ! realpath "$cleanupfile" >/dev/null 2>&1; then
   printf "\n%s\n\n" "Error: Invalid cleanup script path."
   exit 1
 else
@@ -59,48 +66,47 @@ fi
 confirm() {
   local OPTIND
   local strict=0
-  local yes="y" 
+  local yes="y"
   local no="n"
   local left="["
   local right="]"
   local grep="--ignore-case --quiet" # Default grep flags
-  local prompt="Continue?" # Default message
+  local prompt="Continue?"           # Default message
 
-  for arg in "$@"
-  do
+  for arg in "$@"; do
     case $arg in
-      # Right side of prompt
-      -r|--right)
+    # Right side of prompt
+    -r | --right)
       shift
       right="$1"
       ;;
-      # Left side of prompt
-      -l|--left)
+    # Left side of prompt
+    -l | --left)
       shift
       left="$1"
       ;;
-      # Strict mode requires uppercase for yes
-      -s|--strict)
+    # Strict mode requires uppercase for yes
+    -s | --strict)
       strict=1
       shift
       ;;
-      # Option to display for yes
-      -y|--yes)
+    # Option to display for yes
+    -y | --yes)
       shift
       yes="$1"
       ;;
-       # Option to display for no
-      -n|--no)
+      # Option to display for no
+    -n | --no)
       shift
       no="$1"
       ;;
-      # Show usage information
-      -h|--help)
+    # Show usage information
+    -h | --help)
       help="$1"
       shift
       ;;
-      # The remaining is used as prompt
-      *)
+    # The remaining is used as prompt
+    *)
       prompt="$@"
       shift
       ;;
@@ -241,6 +247,16 @@ fi
 
 printf "\n"
 
+# Ask about Foot
+if confirm --strict "Enable for Foot (rm -rf ~/.config/foot)?"; then
+  printf "\n"
+  loudly "rm -rf ~/.config/foot"
+  loudly "ln -s /etc/nixos/config/foot ~/.config/foot"
+  cleanup="$cleanup\nrm ~/.config/foot"
+fi
+
+printf "\n"
+
 # Ask about Tridactyl
 if confirm --strict "Enable for Tridactyl (rm -rf ~/.config/tridactyl)?"; then
   printf "\n"
@@ -277,7 +293,7 @@ printf "\n"
 # least one configuration.
 if [ -n "$cleanup" ]; then
   # Write script
-  printf "$cleanupbang\n$cleanup\nrm $cleanupfile" > "$cleanupfile"
+  printf "$cleanupbang\n$cleanup\nrm $cleanupfile" >"$cleanupfile"
   chmod u+x "$cleanupfile"
 
   # Show result message
@@ -288,4 +304,3 @@ else
 fi
 
 exit 0
-
